config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

app/models/page.rb
class Page < ActiveRecord::Base
	def category_enum
		['Networking', 'Mobile aplication']
		
	end
	validates :name, :title, :section, :category, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@pag=Page.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Topbrainz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<nav class="navbar navbar-default">
<div class="container">
<ul class="nav navbar-nav">
	<li class="active"><%= link_to "Home", root_path %></li>	
</ul>

<ul class="nav navbar-nav navbar-right">
	<li><%= link_to "Admin", rails_admin_path %></li>
</ul>
</div>
</nav>
<!-- This is how to read information from the database -->
<div>
<table class="table table-bordered table-hover" cellpadding="10" cellspacing="0">
	<caption class="col-sm-offset-5"><h2>MY RECORDS</h2></caption>
	<thead><strong>
		<td>NAME</td>
		<td>TITLE</td>
		<td>CATEGORY</td>
		<td>TIME</td>
	</strong></thead>
	<tbody>
	<% @pag.each do |g| %>
		<td><%= g.name %></td>
		<td><%= g.title %></td>
		<td><%= g.category %></td>
		<td><%= time_ago_in_words(g.created_at, include_seconds: true) %> ago</td>
		 <% end %> 
	</tbody>
</table>
</div>